.github/workflows/deploy.yaml, .travis.yml
[AB#604](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/604)
```
[ ] Yes
[ ] No
```
=> Add github action for publishing

source/standards/api-documentation.html.md.erb, source/standards/apis.html.md.erb, source/ways-of-working/pull-requests.html.md.erb
=> Update last reviewed date

source/standards/api-documentation.html.md.erb
=> Update requirements for OpenAPI Spec 3.0

config/tech-docs.yml, source/onboarding/person/index.html.md.erb, source/ways-of-working/new-component/helm-chart.html.md.erb, source/ways-of-working/new-component/index.html.md.erb
[AB#775](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/775)
```
[ ] Yes
[ ] No
```
=> Add helm chart guide

source/onboarding/team/index.html.md.erb
=> Adding Jenkins Org setup instructions

source/ways-of-working/new-component/github-repo.html.md.erb, source/ways-of-working/new-component/helm-chart.html.md.erb, source/ways-of-working/new-component/index.html.md.erb
=> adding github repo guidelines

source/ways-of-working/new-component/index.html.md.erb, source/ways-of-working/new-component/secrets-management.html.md.erb
=> Adding secret management documentation

source/ways-of-working/new-component/secrets-management.html.md.erb
=> Fixing typo in link

source/ways-of-working/common-pipeline/index.html.md.erb, source/ways-of-working/new-component/gitops-flux.html.md.erb, source/ways-of-working/new-component/index.html.md.erb
=> Adding gitops, flux documentation

source/ways-of-working/principles/index.html.md.erb
=> Adding link to gitops

source/ways-of-working/path-to-live/load-balancer-configuration.html.md.erb
Fix URL for load balancer
```
[ ] Yes
[ ] No
```
=> Fix URL for load balancer

source/ways-of-working/path-to-live/front-door.html.md.erb
=> Fix broken link

source/ways-of-working/new-component/elasticsearch.html.md.erb
=> moving elastic search to right hierarchy

source/ways-of-working/new-component/secrets-management.html.md.erb
=> Add warning for keyvault

source/ways-of-working/new-component/secrets-management.html.md.erb
=> changing to warning style

.github/workflows/deploy.yaml, source/ways-of-working/new-component/gitops-flux.html.md.erb
Had to send this 4,5 times today.
```
[ ] Yes
[x] No
```
=> Adding basic trouble shooting steps for gitops

source/onboarding/team/index.html.md.erb
Fixes https://github.com/hmcts/hmcts.github.io/issues/55
=> Reorder team onboarding page

source/ways-of-working/new-component/secrets-management.html.md.erb
=> Change managed identity instructions to use key vault module

source/ways-of-working/new-component/secrets-management.html.md.erb
=> Fix link to keyvault application access

source/ways-of-working/new-component/secrets-management.html.md.erb
=> Updating review date for secret mgmt

source/ways-of-working/new-component/gitops-flux.html.md.erb
=> Update flux config instructions

source/onboarding/index.html.md.erb, source/onboarding/person/index.html.md.erb, source/onboarding/team/index.html.md.erb
=> Updating onboarding documentation

source/ways-of-working/new-component/github-repo.html.md.erb
Super Humans lost their magical powers
=> Bots not needed for jennkins anymore

source/ways-of-working/asking-for-help/index.html.md.erb, source/ways-of-working/new-component/infrastructure-as-code.html.md.erb, source/ways-of-working/path-to-live/front-door.html.md.erb, source/ways-of-working/path-to-live/public-dns.html.md.erb
=> Replace PE references

source/information-security/certificate-automation.html.md.erb, source/information-security/index.html.md.erb
https://tools.hmcts.net/jira/browse/CYBER-1458
Sourced from: https://ministryofjustice.github.io/security-guidance/automated-certificate-renewal/#automated-certificate-renewal
Document proposed policy for automated certification rotation
```
[ ] Yes
[ ] No
```
=> CYBER-1458 Add automated certificate rotation policy

.gitignore, Gemfile.lock, source/onboarding/index.html.md.erb, source/onboarding/person/index.html.md.erb
Making some updates based on learnings from onboarding some DTS Civil Servants
```
[ ] Yes
[X] No
```
=> Updates to onboarding process for individuals

source/onboarding/person/index.html.md.erb, source/onboarding/team/index.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-1187
=> DTSPO-1187 Updated GitHub user onboarding process

source/onboarding/person/index.html.md.erb
=> Update standard access

source/api-docs/index.html.md.erb
=> Update API documentation

source/ways-of-working/index.html.md.erb, source/ways-of-working/new-component/gitops-flux.html.md.erb, source/ways-of-working/troubleshooting/index.html.md.erb
=> Adding detailed steps on debugging gitops issues

source/onboarding/person/index.html.md.erb
=> Fixes link to Azure AD groups repo/file

source/ways-of-working/troubleshooting/index.html.md.erb
Warning added to Troubleshoot page
```
[ ] Yes
[ x] No
```
=> Add warning about using delete privilege on non-prod

source/ways-of-working/troubleshooting/index.html.md.erb
=> Add more trubleshooting steps

source/ways-of-working/troubleshooting/index.html.md.erb
=> Add project disabled in Jenkins

source/information-security/certificate-automation.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-2610
```
[ ] Yes
[x] No
```
=> DTSPO-2610 Add information for LetsENcrypt Cert Renewals

source/ways-of-working/new-component/helm-chart.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-2706
waqys of working to reflect the advanced values templates for preview environment.
screenshot from middleman server - ![image](https://user-images.githubusercontent.com/33876448/127137142-5400a196-322f-4880-a0fa-591909265366.png)
```
[ ] Yes
[X ] No
```
=> added section for advanced values

source/ways-of-working/troubleshooting/index.html.md.erb
=> change to new aks clusters

source/ways-of-working/new-component/flux-v1.html.md.erb, source/ways-of-working/new-component/gitops-flux.html.md.erb
=> adding flux v2 overview

source/onboarding/team/jenkins.html.md.erb, source/stylesheets/screen.css.scss, source/ways-of-working/common-pipeline/common-pipeline.html.md.erb, source/ways-of-working/common-pipeline/index.html.md.erb
=> DTSPO-4882 Add bi-directional link between pipeline and onboarding

ways-of-working/troubleshooting/fluxV1.html
=> DTSPO-4882 Fix Typo

source/ways-of-working/troubleshooting/fluxV1.html.md.erb
=> DTSPO-4882: fix typo

source/ways-of-working/common-pipeline/index.html.md.erb
link was previously 404
```
[ ] Yes
[x ] No
```
=> Update index page to have correct link for helm

source/ways-of-working/troubleshooting/_clusters.md
=> Update preview naming convention

source/onboarding/team/jenkins.html.md.erb
CFT now uses hmcts-jenkins-cft, and SDS uses hmcts-jenkins-cnp (could create an sds one at some point)
=> Remove instructions for creating a new app

source/onboarding/person/index.html.md.erb
I wanted to add the golden path here but I think it makes sense to restructure the page a bit first
=> Refactor onboarding page a bit

.github/workflows/deploy.yaml
=> let's try v2

source/ways-of-working/guides/index.html.md.erb, source/ways-of-working/guides/profile-java-app-in-aks.html.md.erb
=> New guide for profiling java apps on AKS

source/ways-of-working/guides/profile-java-app-in-aks.html.md.erb
html is a bit knarly when you have a line break within a code block so have taken those out.
```
[ ] Yes
[X] No
```
=> Removed line breaks in code blocks

source/onboarding/person/index.html.md.erb
Draft till we've tested it with a few users.
=> DTSPO-5954 Add golden path to onboarding

source/ways-of-working/troubleshooting/_clusters.md
Update CFT cluster naming for ithc & ptl
```
[ ] Yes
[X] No
```
=> Update CFT cluster naming for ithc & ptl

source/ways-of-working/asking-for-help/index.html.md.erb
- `idam-support` channel has been replaced with `idam-support-cft`, updated docs to reflect this.
```
[ ] Yes
[x] No
```
=> Updated 'asking-for-help' with new IDAM support slack channel

source/ways-of-working/troubleshooting/_clusters.md
Figured we can just swap the active one around rather than putting both in?
=> Update demo cluster

source/glossary/index.html.md.erb, source/information-security/certificate-automation.html.md.erb, source/information-security/index.html.md.erb, source/onboarding/index.html.md.erb, source/ways-of-working/common-pipeline/publishing-libraries/java.html.md.erb, source/ways-of-working/common-pipeline/publishing-libraries/nodejs.html.md.erb, source/ways-of-working/common-pipeline/tips_and_tricks.html.md.erb, source/ways-of-working/environments/index.html.md.erb, source/ways-of-working/index.html.md.erb, source/ways-of-working/new-component/elasticsearch.html.md.erb, source/ways-of-working/new-component/feature-flags.html.md.erb, source/ways-of-working/new-component/flux-v1.html.md.erb, source/ways-of-working/new-component/helm-chart.html.md.erb, source/ways-of-working/new-component/index.html.md.erb, source/ways-of-working/new-component/infrastructure-as-code.html.md.erb, source/ways-of-working/new-component/secrets-management.html.md.erb, source/ways-of-working/path-to-live/tls-certificates.html.md.erb, source/ways-of-working/troubleshooting/fluxV1.html.md.erb
=> Review pages

source/ways-of-working/guides/profile-java-app-in-aks.html.md.erb
N/A
Updating guide for java profiling
```
[ ] Yes
[X] No
```
=> Updating guide for java profiling

source/index.html.md.erb, source/onboarding/team/jenkins.html.md.erb, source/ways-of-working/troubleshooting/fluxV1.html.md.erb, source/ways-of-working/troubleshooting/index.html.md.erb
=> Add more troubleshooting steps

source/ways-of-working/troubleshooting/fluxV1.html.md.erb, source/ways-of-working/troubleshooting/index.html.md.erb
=> Fix broken links for v1 troubleshooting

source/ways-of-working/environments/external-access.html.md.erb
Removing redirect URL documentation as it is now automated.
```
[ ] Yes
[x] No
```
=> DTSPO-10175 - remove documentation on adding redirect URL

source/ways-of-working/troubleshooting/_clusters.md
update cft prod to new cluster naming
```
[ ] Yes
[X] No
```
=> update cft prod to new cluster naming

source/ways-of-working/new-component/github-repo.html.md.erb, source/ways-of-working/standards/pull-requests.html.md.erb
Adding recommended Branch Protection Rules for new Repositories
```
[ ] Yes
[ x ] No
```
=> Add Recommended Branch Rules

source/ways-of-working/oat/index.html.md.erb, source/ways-of-working/path-to-live/index.html.md.erb, source/ways-of-working/troubleshooting/_clusters.md
=> Adding OAT documentation for teams to follow before raising a OAT request

source/ways-of-working/asking-for-help/index.html.md.erb, source/ways-of-working/guides/index.html.md.erb, source/ways-of-working/new-component/flux-v1.html.md.erb, source/ways-of-working/new-component/github-repo.html.md.erb, source/ways-of-working/new-component/gitops-flux.html.md.erb, source/ways-of-working/new-component/helm-chart.html.md.erb, source/ways-of-working/new-component/index.html.md.erb, source/ways-of-working/new-component/infrastructure-as-code.html.md.erb, source/ways-of-working/path-to-live/index.html.md.erb, source/ways-of-working/principles/index.html.md.erb, source/ways-of-working/troubleshooting/index.html.md.erb
=> Shuffle pages around to more meaningful order

source/ways-of-working/guides/index.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-10290
Fix review date on guides page
```
[ ] Yes
[x] No
```
<a href="https://gitpod.io/#https://github.com/hmcts/hmcts.github.io/pull/242"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> DTSPO-10290 - fix review date

source/ways-of-working/troubleshooting/index.html.md.erb
=> change to hr shortname

source/ways-of-working/environments/aks-auto-shutdown.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-12179
Documentation for Auto-Shutdown
```
[ ] Yes
[X] No
```
=> DTSPO-12179 - Documentation for Auto-Shutdown

source/onboarding/index.html.md.erb, source/onboarding/person/index.html.md.erb, source/ways-of-working/common-pipeline/common-pipeline.html.md.erb, source/ways-of-working/new-component/github-repo.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-12517
https://tools.hmcts.net/jira/browse/DTSPO-12518
https://tools.hmcts.net/jira/browse/DTSPO-12513
Reviewed pages & bumped review dates.
```
[ ] Yes
[x] No
```
=> feat: review pages

source/ways-of-working/asking-for-help/index.html.md.erb, source/ways-of-working/standards/db-schema-change.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-12515
https://tools.hmcts.net/jira/browse/DTSPO-12519
```
[ ] Yes
[ ] No
```
=> Changed last review date and everything upto date

source/ways-of-working/environments/aks-auto-shutdown.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-12179
Edit Environment Schedule Documentation
```
[ ] Yes
[X] No
```
=> DTSPO-12179 - Edit Environment Schedule Documentation

source/ways-of-working/environments/sandbox-cleardown.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-12501
Documentation for Sandbox Cleardown
```
[ ] Yes
[X] No
```
=> DTSPO-12501 - Documentation for Sandbox Cleardown

source/cloud-native-platform/environments/sandbox-cleardown.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-12501
Correct Typo
```
[ ] Yes
[X] No
```
=> DTSPO-12501 - Correct Typo

source/cloud-native-platform/environments/external-access-in-demo.html.md.erb
=> Changed last review date

source/cloud-native-platform/guides/flyway-database-migrations.html.md.erb
=> Update review date

source/cloud-native-platform/environments/aks-auto-shutdown.html.md.erb
https://hmcts-reform.slack.com/archives/C6DN09J8G/p1677055585097359
Added comment about weekends
```
[ ] Yes
[X ] No
```
=> added comment about weekends

source/cloud-native-platform/onboarding/team/azuread.html.md.erb, source/cloud-native-platform/onboarding/team/github.html.md.erb, source/cloud-native-platform/onboarding/team/index.html.md.erb, source/cloud-native-platform/onboarding/team/jenkins.html.md.erb, source/cloud-native-platform/onboarding/team/office365.html.md.erb
=> feat: reviewed onboarding child pages

source/cloud-native-platform/standards/db-schema-change.html.md.erb
=> Changed review date

source/cloud-native-platform/standards/pull-requests.html.md.erb
=> Updated last reviewed date

source/cloud-native-platform/path-to-live/front-door.html.md.erb, source/cloud-native-platform/path-to-live/public-dns.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-12635
https://tools.hmcts.net/jira/browse/DTSPO-12636
```
[ ] Yes
[ ] No
```
=> Date updated

source/cloud-native-platform/environments/external-access-in-demo.html.md.erb, source/cloud-native-platform/path-to-live/shutter.html.md.erb
DTSPO-12637
Added useful web link for the creation of CDN
```
[ ] Yes
[ X] No
```
=> Dtspo 12637 shutter

source/cloud-native-platform/troubleshooting/index.html.md.erb
Add guidance on the channel_not_found error message when it refers to a user id not being found
```
[ ] Yes
[x] No
```
=> Add more info on channel_not_found

source/cloud-native-platform/onboarding/team/jenkins.html.md.erb
Fixes https://github.com/hmcts/hmcts.github.io/issues/288
=> Fix link for SDS dashboard

source/cloud-native-platform/onboarding/person/index.html.md.erb
I'll do more follow ups as different parts are enabled
=> DTSPO-13028 Add GitHub group to standard groups

source/cloud-native-platform/path-to-live/index.html.md.erb, source/cloud-native-platform/path-to-live/tls-certificates.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-12843
https://tools.hmcts.net/jira/browse/DTSPO-12845
```
[ ] Yes
[ ] No
```
=> Review date updated

source/cloud-native-platform/new-component/elasticsearch.html.md.erb, source/cloud-native-platform/new-component/feature-flags.html.md.erb, source/cloud-native-platform/new-component/github-repo.html.md.erb, source/cloud-native-platform/new-component/gitops-flux.html.md.erb, source/cloud-native-platform/new-component/helm-chart.html.md.erb, source/cloud-native-platform/new-component/index.html.md.erb, source/cloud-native-platform/new-component/infrastructure-as-code.html.md.erb, source/cloud-native-platform/new-component/secrets-management.html.md.erb
DTSPO-12834
Reviewed and Updated Stating a new component
```
[ ] Yes
[ X] No
```
=> Reviewed and Updated Stating a new component

source/cloud-native-platform/new-component/feature-flags.html.md.erb, source/cloud-native-platform/onboarding/person/index.html.md.erb, source/cloud-native-platform/onboarding/team/github.html.md.erb, source/cloud-native-platform/troubleshooting/index.html.md.erb
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/hmcts/hmcts.github.io/pull/302)
=> DTSPO-13053 Update GitHub onboarding docs

source/cloud-native-platform/onboarding/person/index.html.md.erb
=> Reword Azure AD onboarding docs

source/cloud-native-platform/troubleshooting/_clusters.md
Fixes https://github.com/hmcts/hmcts.github.io/issues/325
=> Add sandbox clusters

.github/actions/spelling/expect.txt, source/cloud-native-platform/guides/automated-dependency-updates.html.md.erb
=> Docs on automated dependency update

.github/workflows/deploy.yaml, source/hmcts-overview/index.html.md.erb
Fixes https://github.com/hmcts/hmcts.github.io/issues/344
=> Fix 404 issue on links

Gemfile, Gemfile.lock
Resolved in https://github.com/alphagov/tech-docs-gem/issues/318 not closed for some reason
Project was upgraded in https://github.com/hmcts/hmcts.github.io/pull/346
=> Remove unneeded workaround

.github/actions/spelling/allow.txt
=> Update allow.txt to flexible server extensions

source/cloud-native-platform/onboarding/team/azuread.html.md.erb
update AAD group creation section on HMCT way 
```
[ ] Yes
[ ] No
```
=> update aad group in HMCTS way

source/cloud-native-platform/onboarding/team/azuread.html.md.erb
=> fix new line

.github/actions/spelling/expect.txt, source/cloud-native-platform/guides/postgresql-singleserver-to-flexibleserver-migration-portal.html.md.erb
=> update Flexible server migration documentation

source/cloud-native-platform/onboarding/person/index.html.md.erb
=> Update ask-for-help link

source/cloud-native-platform/environments/aks-auto-shutdown.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-13971
Update Documentation for aks-auto-shutdown
```
[ ] Yes
[X] No
```
=> DTSPO-13971 - Update Documentation for aks-auto-shutdown

source/cloud-native-platform/environments/aks-auto-shutdown.html.md.erb
[DTSPO-13971](https://tools.hmcts.net/jira/browse/DTSPO-13971)
Add more environments to aks-auto-shutdown schedule
```
[ ] Yes
[X] No
```
=> DTSPO-13971 - Add more environments to aks-auto-shutdown schedule

source/cloud-native-platform/path-to-live/oat.html.md.erb
Review and fix broken link for shuttle 
```
[ ] Yes
[ ] No
```
=> DTSPO-14895-Review Operational Acceptance Testing Documentation

source/cloud-native-platform/api-docs/index.html.md.erb
Review API Documentation Documentation
```
[ ] Yes
[ ] No
```
=> DTSPO-14899 Review API Documentation Documentation

source/cloud-native-platform/common-pipeline/common-pipeline.html.md.erb
Review The common pipeline Documentation
```
[ ] Yes
[ ] No
```
=> DSPO-14900-Review The common pipeline Documentation

source/cloud-native-platform/environments/sandbox-cleardown.html.md.erb, source/cloud-native-platform/onboarding/index.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-14903
https://tools.hmcts.net/jira/browse/DTSPO-14907
Checked n Changed last review date
```
[ ] Yes
[ x] No
```
=> Check n Changed last review date

source/cloud-native-platform/common-pipeline/publishing-libraries/index.html.md.erb, source/cloud-native-platform/onboarding/team/slack.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-14902
https://tools.hmcts.net/jira/browse/DTSPO-14908
DTSPO-14902 & DTSPO-14908 - Review Publishing libraries and Slack Documentation - updated last reviewed date
```
[ ] Yes
[X] No
```
=> DTSPO-14902 & DTSPO-14908 - Review Publishing libraries and Slack Documentation

source/cloud-native-platform/environments/aks-auto-shutdown.html.md.erb
DTSPO-14904
updated aks-auto-shutdown
```
[ ] Yes
[X ] No
```
=> updated aks-auto-shutdown

source/cloud-native-platform/path-to-live/public-dns.html.md.erb
Not needed since we switched to static web apps
=> Remove cdnverify references

source/cloud-native-platform/guides/postgresql-singleserver-to-flexibleserver-migration-dms.html.md.erb
add comment to reference Azure Portal
```
[ ] Yes
[X] No
```
=> add comment to reference Azure Portal

source/cloud-native-platform/onboarding/person/index.html.md.erb
Fixes https://github.com/hmcts/hmcts.github.io/issues/383
I've verified the docs are working:
=> Clarify VPN requirement

source/cloud-native-platform/troubleshooting/index.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-15513
Reviewed documentation  and updated 'last reviewed date'
=> DTSPO-15513 - Review of Documentation - Updated last reviewed date

source/cloud-native-platform/standards/pull-requests.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-15511
DTSPO-15511 - Review of documentation and updated last reviewed date
=> DTSPO-15511 - Review of documentation and updated last reviewed date 

source/cloud-native-platform/standards/index.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-15510
DTSPO-15510 - Review of documentation and updated last reviewed date
=> DTSPO-15510 - Review of documentation and updated last reviewed date

source/cloud-native-platform/path-to-live/tls-certificates.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-15508
Updated URL link to Managed Certificate limitations and updated last reviewed date
=> DTSPO-15508 - Updated link to Managed Certificate limitations & last reviewed date

source/cloud-native-platform/path-to-live/load-balancer-configuration.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-15506
DTSPO-15506 - Reviewed documentation (including links) and updated last reviewed date.
=> DTSPO-15506 - Reviewed documentation (including links) & updated last reviewed date.

source/cloud-native-platform/new-component/github-repo.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-15616
Reviewed documentation (including links) and updated late reviewed date
=> DTSPO-15616 - Reviewed Documentation for 'Create a Github Repository'

source/cloud-native-platform/guides/postgresql-singleserver-to-flexibleserver-migration-dms.html.md.erb
[DTSPO-14390](https://tools.hmcts.net/jira/browse/DTSPO-14390)
Update DMS documentation with limitation
=> DTSPO-14390 - Update DMS documentation with limitation

source/cloud-native-platform/onboarding/team/index.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-15612
Reviewed documentation including links and updated last reviewed date
=> DTSPO-15612 - Reviewed documentation including links & updated last reviewed date

source/cloud-native-platform/new-component/secrets-management.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-15663
6 month documentation review - updated Managed Identity information, updated links and last reviewed date
=> DTSPO-15663 - Updated links, Managed/Workload Identity and last reviewed date

source/cloud-native-platform/new-component/infrastructure-as-code.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-15617
6 month documentation review for 'Infrastructure as Code' - Updated Secrets Management link and last reviewed date
=> DTSPO-15663 - Updated Secrets Management link & last reviewed date

source/cloud-native-platform/common-pipeline/index.html.md.erb
modify the common pipeline page
=> modify the common pipeline page

source/cloud-native-platform/new-component/index.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-15615
6 month documentation review - updated last reviewed date
=> DTSPO-15615 - 'Starting a new component' Documentation review - updated last reviewed date

source/cloud-native-platform/new-component/helm-chart.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-15662
'Helm Chart' 6 month documentation review - Removed reusable jobs as these no longer exist. Updated link to correct slack channel and updated last reviewed date
=> DTSPO-15662 - 'Helm Chart' 6 month documentation review

.github/actions/spelling/expect.txt, source/cloud-native-platform/path-to-live/_front-door-config.md, source/cloud-native-platform/path-to-live/_front-door-endpoints.md, source/cloud-native-platform/path-to-live/public-dns.html.md.erb
Verification using CNAME isn't working on the new frondoors hence we need to verify it using the TXT records.
=> Verify custom domain using TXT record

source/cloud-native-platform/path-to-live/_front-door-config.md
https://tools.hmcts.net/jira/browse/DTSPO-15720
Removed add_txt_record
=> removed add_txt_record from fd config

source/cloud-native-platform/path-to-live/_front-door-config.md
=> added dns_zone_name

source/cloud-native-platform/new-component/infrastructure-as-code.html.md.erb
add module search to include terraform-module-*
=> add module search to include terraform-module-*

source/cloud-native-platform/health-end-points/index.html.md.erb
[DTSPO-14035](https://tools.hmcts.net/jira/browse/DTSPO-14035)
adding documentation for health endpoints
=> DTSPO-14035 document recommendations on health end points

source/cloud-native-platform/common-pipeline/publishing-libraries/index.html.md.erb, source/cloud-native-platform/common-pipeline/publishing-libraries/java.html.md.erb, source/cloud-native-platform/common-pipeline/publishing-libraries/nodejs.html.md.erb, source/cloud-native-platform/environments/external-ip-addresses.html.md.erb, source/cloud-native-platform/glossary/index.html.md.erb, source/standards/index.html.md.erb, source/standards/practices/index.html.md.erb, source/standards/principles/index.html.md.erb, source/standards/standards/index.html.md.erb, source/standards/technology-stack/index.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-15460
Index pages with little content but they show as null on main api json output, better to add a long review date than leave it as null
=> Index pages missing values and showing as null

source/cloud-native-platform/troubleshooting/_clusters.md
Update _clusters.md with ss-demo-01
=> Update _clusters.md with ss-demo-01

source/cloud-native-platform/onboarding/index.html.md.erb, source/cloud-native-platform/onboarding/team/slack.html.md.erb
Update review dates on pages that are due
=> Update review dates

source/cloud-native-platform/onboarding/index.html.md.erb
=> Fix typo in review date

source/cloud-native-platform/path-to-live/shutter.html.md.erb
=> Update shuttering process

source/cloud-native-platform/path-to-live/public-dns.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-16109
Updated Read me file to add notes for public to private dns sync
=> DTSPO-16109 - added read me for dns sync

.github/actions/spelling/expect.txt, source/cloud-native-platform/path-to-live/shutter.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-16428
Updating DNS Shuttering documentation to match new method
=> Updating DNS Shuttering documentation to match new method

source/cloud-native-platform/new-component/elasticsearch.html.md.erb, source/cloud-native-platform/path-to-live/front-door.html.md.erb, source/cloud-native-platform/path-to-live/load-balancer-configuration.html.md.erb, source/cloud-native-platform/path-to-live/tls-certificates.html.md.erb, source/cloud-native-platform/standards/db-schema-change.html.md.erb, source/cloud-native-platform/standards/index.html.md.erb, source/cloud-native-platform/standards/pull-requests.html.md.erb, source/cloud-native-platform/troubleshooting/index.html.md.erb
Review and update review dates for expired pages
=> Review and update review dates for expired pages

.github/actions/spelling/allow.txt, .github/actions/spelling/expect.txt, source/cloud-native-platform/path-to-live/shutter.html.md.erb
- Updates docs to use frontdoor endpoint IP instead of app gateway IP
=> Update access shuttered docs

source/cloud-native-platform/environments/index.html.md.erb, source/cloud-native-platform/guides/automated-dependency-updates.html.md.erb, source/cloud-native-platform/new-component/github-repo.html.md.erb, source/cloud-native-platform/new-component/index.html.md.erb, source/cloud-native-platform/new-component/infrastructure-as-code.html.md.erb, source/cloud-native-platform/new-component/secrets-management.html.md.erb, source/cloud-native-platform/onboarding/index.html.md.erb, source/cloud-native-platform/onboarding/person/index.html.md.erb, source/cloud-native-platform/path-to-live/public-dns.html.md.erb
Reviewing pages with expired review date from daily checks
=> Reviewing pages with expired review date from daily checks

source/cloud-native-platform/onboarding/team/index.html.md.erb
=> Update expired review page

source/cloud-native-platform/environments/sandbox-cleardown.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-17731
Updated default days to 14
=> DTSPO-17731 - change expiresAfter default days to 14

.github/actions/spelling/allow.txt, source/standards/standards/frontend-web-performance.html.md.erb
https://tools.hmcts.net/jira/browse/DTSSE-4983
Created a separate section under principles in the HMCTS Way for Frontend Web Performance best practice. It lists changes that can be made for services on any frontend architecture to improve overall performance of a service's Frontend code. This guidance is framework-agnostic. See #454 for comments and feedback.
=> Updated the frontend web performance recommendations following feedback

source/cloud-native-platform/path-to-live/shutter.html.md.erb
Updates to check for all cft services to be shuttered
=> Updates to check for all cft services to be shuttered

source/cloud-native-platform/health-end-points/index.html.md.erb
Review daily check pages that have expired
=> Review daily check pages that have expired

source/cloud-native-platform/path-to-live/shutter.html.md.erb
- Adds another example for tagging zone/record with CFT
- Improve wording
=> Update shuttering docs with more examples

source/cloud-native-platform/path-to-live/shutter.html.md.erb
- Made some changes to shuttering in https://github.com/hmcts/azure-public-dns/pull/1786 
- Just updating docs to match current process
=> Update docs to match new shuttering process

source/cloud-native-platform/path-to-live/shutter.html.md.erb
- Updated a link in shuttering docs to reflect the current setup
=> Update link to example

source/cloud-native-platform/path-to-live/shutter.html.md.erb
=> Replace link that includes outdated wording

source/cloud-native-platform/onboarding/person/index.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-17204
Adding some guidance to tell new joiners to request the SC package when they join
Duration has been increased to make it less annoying for people https://github.com/hmcts/azure-access-packages/pull/73
=> DTSPO-17204 - add guidance on security clearance

source/cloud-native-platform/path-to-live/public-dns.html.md.erb
Remove 'Create afdverify CNAME' step as its not needed.
=> remove  afdverify as its not needed

source/cloud-native-platform/environments/auto-shutdown.html.md.erb, source/standards/standards/angular-web-performance.html.md.erb
n/a
Reviewed auto-shutdown documentation - updating review date
Removed broken link
=> Reviewed auto-shutdown documentation - updating review date

source/cloud-native-platform/onboarding/person/index.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-18356
Added documentation for Microsoft Entra invite
=> DTSPO-18356 - Added documentation for guest invites

.github/workflows/build.yaml, .github/workflows/deploy.yaml, .gitignore, Rakefile, config/tech-docs.yml, source/cloud-native-platform/guides/creating-a-new-subscription.html.md.erb, source/cloud-native-platform/new-component/gitops-flux.html.md.erb
Recommended by GitHub and makes my next PR simpler
Previously we used auto pages build on publish to the `master` branch which has caused confusion before
=> Switch to GitHub actions to deploy site

.ci/trigger-index.sh, .ci/upload.sh, .github/actions/spelling/expect.txt, .github/workflows/deploy.yaml
Part of https://github.com/hmcts/slack-help-bot/issues/382
=> Add upload of files

source/cloud-native-platform/troubleshooting/index.html.md.erb
- Moved VPN docs off the bottom as I'm very used to AKS being at the bottom and its the most common thing I use on that page
- Add some more self help steps
- Added a minimal explainer on why disabling ipv6 is needed
- Minor rewording
- Simplified TOC a bit
=> Improve VPN troubleshooting docs

.ci/install-htmlq.sh, .github/workflows/deploy.yaml
Azure cli task is run inside of a container so installing htmlq outside of it didn't work, hopefully this works otherwise I'll change it to run on PR on the next attempt :p
=> Install htmlq inside of the container

source/cloud-native-platform/troubleshooting/index.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-18493
Adding some advice on a couple of sonar scan errors that appeared recently.
=> DTSPO-18493 - Sonar scan troubleshooting

source/cloud-native-platform/troubleshooting/index.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-18493
Remove a couple of duplicated items around sonar scans
Move a couple of sections
Update review date
=> DTSPO-14893 - remove duplicated items, update date

source/cloud-native-platform/guides/flyway-database-migrations.html.md.erb, source/cloud-native-platform/guides/managing-manual-key-vault-secrets.html.md.erb, source/cloud-native-platform/guides/postgresql-singleserver-to-flexibleserver-migration-dms.html.md.erb, source/cloud-native-platform/guides/postgresql-singleserver-to-flexibleserver-migration-portal.html.md.erb, source/legacy/index.html.md.erb, source/legacy/knowledgebase/index.html.md.erb, source/legacy/support/index.html.md.erb
Reviewing daily checks expired pages
=> Reviewing daily checks expired pages

source/cloud-native-platform/asking-for-help/index.html.md.erb, source/cloud-native-platform/common-pipeline/common-pipeline.html.md.erb, source/cloud-native-platform/common-pipeline/publishing-libraries/java.html.md.erb, source/cloud-native-platform/common-pipeline/publishing-libraries/nodejs.html.md.erb, source/cloud-native-platform/environments/external-ip-addresses.html.md.erb, source/cloud-native-platform/guides/afd-waf.html.md.erb, source/cloud-native-platform/guides/connect-via-vpn.html.md.erb, source/cloud-native-platform/guides/pr-url.html.md.erb, source/cloud-native-platform/guides/profile-java-app-in-aks.html.md.erb, source/cloud-native-platform/new-component/elasticsearch.html.md.erb, source/cloud-native-platform/new-component/feature-flags.html.md.erb, source/cloud-native-platform/new-component/gitops-flux.html.md.erb, source/cloud-native-platform/onboarding/team/azuread.html.md.erb, source/cloud-native-platform/onboarding/team/github.html.md.erb, source/cloud-native-platform/onboarding/team/jenkins.html.md.erb, source/cloud-native-platform/path-to-live/oat.html.md.erb
As part of the daily checks in dtspo-daily-checks - A list of pages required a review which this PR covers.  This PR covers the list of expired page reviews and updated as necessary
=> Review of expired pages as listed in dtspo-daily-checks

source/cloud-native-platform/api-docs/index.html.md.erb, source/cloud-native-platform/guides/automated-dependency-updates.html.md.erb, source/cloud-native-platform/onboarding/team/slack.html.md.erb, source/cloud-native-platform/path-to-live/index.html.md.erb, source/cloud-native-platform/standards/apis.html.md.erb, source/standards/standards/angular.html.md.erb
Reviewing and updating review dates for HMCTS Way pages from daily checks
=> Reviewing and updating review dates for HMCTS Way pages from daily checks

source/cloud-native-platform/api-docs/index.html.md.erb, source/cloud-native-platform/path-to-live/shutter.html.md.erb, source/cloud-native-platform/standards/apis.html.md.erb
- Reviewed docs for shuttering
- Updated `last_reviewed_on` date for these and some API docs
=> Review Shuttering docs

source/cloud-native-platform/environments/auto-shutdown.html.md.erb
Updating link to correct manual jobs
=> Updating link to correct manual jobs 

source/cloud-native-platform/new-component/elasticsearch.html.md.erb
- Temporarily updating elasticsearch documentation about auto restart job over Christmas break
=> Temp update elasticsearch docs

source/cloud-native-platform/path-to-live/oat.html.md.erb
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
Updating OAT for Crime Releases
=> Updating OAT for Crime Releases

source/cloud-native-platform/troubleshooting/index.html.md.erb
See [DTSPO-25106](https://tools.hmcts.net/jira/browse/DTSPO-25106)
Updates troubleshooting guide with nodeJS deployment issues
=> docs: update troubleshooting guide

source/cloud-native-platform/guides/postgresql-singleserver-to-flexibleserver-migration-dms.html.md.erb, source/cloud-native-platform/guides/postgresql-singleserver-to-flexibleserver-migration-portal.html.md.erb, source/cloud-native-platform/new-component/feature-flags.html.md.erb, source/cloud-native-platform/new-component/github-repo.html.md.erb, source/cloud-native-platform/new-component/helm-chart.html.md.erb, source/cloud-native-platform/new-component/infrastructure-as-code.html.md.erb, source/cloud-native-platform/onboarding/person/index.html.md.erb, source/cloud-native-platform/onboarding/team/github.html.md.erb, source/cloud-native-platform/onboarding/team/jenkins.html.md.erb, source/cloud-native-platform/onboarding/team/slack.html.md.erb, source/cloud-native-platform/path-to-live/oat.html.md.erb, source/cloud-native-platform/path-to-live/public-dns.html.md.erb, source/cloud-native-platform/path-to-live/tls-certificates.html.md.erb, source/cloud-native-platform/standards/db-schema-change.html.md.erb, source/cloud-native-platform/standards/pull-requests.html.md.erb
See [DTSPO-26163](https://tools.hmcts.net/jira/browse/DTSPO-26163)
Review of daily checks expired pages - 'reviewed on' dates updated
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> Review of daily checks expired pages

source/cloud-native-platform/environments/external-ip-addresses.html.md.erb
See [DTSPO-26571](https://tools.hmcts.net/jira/browse/DTSPO-26571)
Update external IP addresses for non-production and production hubs.
Compiled locally.
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> Update external IP addresses for non-production and production hubs
