source/standards/api-documentation.html.md.erb
Daring fireball doesn't support images linking to a place that aren't
the image
=> Fix markdown incompatibility

source/index.html.md.erb, source/ways-of-working/pull-requests.html.md.erb
https://tools.hmcts.net/jira/browse/RPE-927
The initial driver for this PR was due to running out of resources on our preview AKS cluster, instead of forcing cleanup of old resources we're instead trying to address this problem at the source by cleaning up old PRs and automating the closure of PRs that have been sitting around for awhile
It seemed weird to write just about that, so I wrote about PRs in general and added the automation around closing PRs as a section inside the PR topic
Open to all feedback, happy to sit with someone and go through it, restructuring as needed etc
=> RPE-927 Guidance on pull requests

Gemfile.lock, config/tech-docs.yml
Now that 1.8.0 of the tech docs is released we can fix our source link
=> Update versions and fix source link

.github/workflows/deploy.yaml
to fix failed deployment from github action
Ref: https://github.com/JamesIves/github-pages-deploy-action/issues/48
If this doesn't work we can add our own access token to the github secrets and that will work apparently...
=> Try lock checkout to a version

source/ways-of-working/troubleshooting/index.html.md.erb
Warning symbol not working
```
[ ] Yes
[ x] No
```
=> Remove warning symbol

source/api-docs/index.html.md.erb
azure bugs are long fixed with openapi v3
=> Drop openapi v2, make API standards more discoverable

source/ways-of-working/path-to-live/tls-certificates.html.md.erb
I was conflicted on whether I should remove the section or just update the link, a user contacted me today confused as our advice conflicted with the main page.
=> Update TLS certificates section in path to live

config/tech-docs.yml
Can be overridden per page if others own certain pages
=> Set slack domain and default owner

config/tech-docs.yml
Fixes slack links not having protocol in them
=> Add https to config

source/cloud-native-platform/onboarding/team/slack.html.md.erb, source/cloud-native-platform/troubleshooting/index.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-7637
Update docs with info on how to fix a failing pipeline due to slack related `not_in_channel` error
```
[ ] Yes
[x] No
```
=> DTSPO-7637 - update docs with pipeline channel error guidance

source/cloud-native-platform/api-docs/index.html.md.erb
Updated the documentation to reflect the move from reform-api-docs to cnp-api-docs
=> Update references to reform-api-docs

source/standards/standards/java.html.md.erb
These standards should be generic enough to apply across all of HMCTS (including Crime). I have stopped short of recommending Gradle over Maven and Ant, and a particular framework like Spring Boot.
=> Add page on Java standards

.github/actions/spelling/expect.txt, source/cloud-native-platform/new-component/helm-chart.html.md.erb
https://tools.hmcts.net/jira/browse/DTSPO-17358
Adding additional documentation about creating Azure resources in charts that use Azure DevOps for publishing
=> Adding additional documentation about creating Azure resources in charts that use Azure DevOps for publishing

.github/actions/spelling/expect.txt, source/cloud-native-platform/path-to-live/shutter.html.md.erb
- Adds a section under `Shuttering Errors` about DNS records falling out of terraform state.
- Issue came up on a recent release
=> Add tf state error to shuttering docs

source/cloud-native-platform/environments/auto-shutdown.html.md.erb, source/cloud-native-platform/new-component/feature-flags.html.md.erb
Updated schedule
https://github.com/hmcts/auto-shutdown/actions/runs/8929073643/job/24526044569
Removed a line from feature flag page, the deleting a trail account content has been fully removed from LD site - which seems to be because multiple accounts on one email address is supported https://docs.launchdarkly.com/home/account/multiple-accounts
=> Fix shutdown/startup page

source/cloud-native-platform/path-to-live/shutter.html.md.erb
- Adds a section explaining how shuttered apps can be accessed for testing changes etc
- Uses plum sbox as an example
=> Add docs for accessing a shuttered app

Rakefile
New pages cause the link checker to fail because they have not been published yet
This is difficult to get around because they will only return 200 code when the publish step happens in the main build, but this can't happen unless the link checker is all happy...
To get around this, we can ignore URLs that are related to this single repo (not including internal hash) -- this allows you to check in new files that won't cause the link checker to break prematurely
Maybe a better way around this with more time to do with checking if a file is being updated or is new and using pipeline conditionals etc - not sure how nice this is with github actions though
=> Update to allow new pages

.github/workflows/deploy.yaml
The permission grant was added to try fixed forked PRs but there's more work needed, this breaks deployment (could be fixed by adding more permissions but lets roll this back till its a more conscious change)
=> Remove explicit permission grant

.ci/install-azcopy.sh, .ci/install-htmlq.sh, .ci/upload.sh, .github/actions/spelling/expect.txt, .github/workflows/build.yaml, .github/workflows/deploy.yaml
https://github.com/hmcts/slack-help-bot/issues/382
Installs dependencies and adds flags needed to make azcopy work, tested on a branch
=> Rework scripts for syncing content

source/cloud-native-platform/path-to-live/tls-certificates.html.md.erb
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
=> Formatting fix
